config/routes.rb
Rails.application.routes.draw do

  # resources :cart_items
  resources :addresses
  resources :reviews
  devise_for :users
  get 'home/index'
  get 'home/bsupplier'
  get 'home/brequirement'
  get 'home/sadvertise'
  get 'home/spost'
  get 'home/cbuy'
  get 'home/csection'
  get 'home/about'
  get 'home/contact'
  root 'home#index'
  get 'product_details/:id' => "home#product_details", as: :product_details
  get 'category_details/:id/products' => "home#category_details", as: :category_details
  get "wishlist" => "products#wishlist"
  get "favorite" => "products#favorite" 
  resources :products, except: [:new, :index, :edit, :show] do
    get :add_wishlist
    get :remove_wishlist
    get :add_favorite
    get :remove_favorite
    get :add_cart
    get :remove_cart 
    member do
      get :report_pdf
    end
  end
  get "/update_cart_item_quantity/:type/:cart_item_id" => "carts#update_cart_item_quantity", as: :update_cart_item_quantity

  get 'order_pdf' => 'orders#order_pdf'

   resources :orders
    
  resources :carts do
  # resources :orders
  end

  namespace :admin, module: nil  do
    root "admin#index"
    resources :users
    resources :products
    resources :categories
    # resources :orders
    get 'deleted_product' => 'products#deleted_product'
    get 'order_product' => 'orders#order_product'
    get 'display_report' => 'admin#display_report' 
    get 'order' => 'admin#order'

    
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user, optional: true
	 # has_many :orders, dependent: :destroy

	def full_address
		"#{address} #{district} #{country}-#{post_code}"
	end
end

app/models/cart.rb
class Cart < ApplicationRecord
		# belongs_to :product, optional: true
		belongs_to :user, optional: true
		has_many :cart_items
		has_many :orders, dependent: :destroy
        default_scope {order("created_at desc")}
     def sub_total
     	cart_items.map(&:price).reject {|e| !e.present?}.sum	
	end
	 def quantity
     	cart_items.map(&:quantity).sum	
	end
	
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	  belongs_to :cart
	  belongs_to :product
      default_scope {order(:created_at)}
     def total_price
     	unit_price = quantity * price	
     end
     
 end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	mount_uploader :image, AvatarUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   belongs_to :product, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product, optional: true
	belongs_to :user, optional: true
	belongs_to :cart, optional: true
	has_many :reviews, dependent: :destroy
    
    # belongs_to :address, optional: true
    default_scope {order("created_at desc")}
    def full_address
    "#{address} #{district} #{country}-#{postal_code}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category, optional: true
  has_many :reviews
	mount_uploader :image, AvatarUploader
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  has_many :orders
  has_many :cart_items
  has_many :favorites, dependent: :destroy
	validate :discount_after_price?
  acts_as_paranoid
  default_scope {order("created_at desc")}
  def discount_after_price?
    if discount_price.present? 
      if discount_price.to_i > price.to_i 
        errors.add :discount_price, " ,full price must be less than"
      end
    end   
  end
  def discount_percentage
    if price.present? && price.to_i > 0 && discount_price.present? && discount_price.to_i > 0
      "" + (100 - (discount_price.to_f / price.to_f * 100.0)).round(2).to_s + "%"
    else
      "0.0"
    end
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :product, optional: true
	belongs_to :order, optional: true
	def half_star?
		if ((self.rating/2.0).to_s.split('.')[1].to_i) > 0
			true
		else
			false
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, AvatarUploader
  extend FriendlyId
  friendly_id :first_name, use: :slugged
  def is_admin?
    return true if self.role =="admin"
  end
  has_many :wishlists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :cart
  has_many :reviews, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  GENDER = {:male => "Male", :female => "Female"}

 
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :product, optional: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # flash[:alert] = "You are not authorized to perform this action."

    if params[:search].present?
     @products = Product.where("lower(title) LIKE :prefix OR lower(description) LIKE :prefix", prefix: "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 8)
    else
      @categories = Category.all
      @products = Product.all.paginate(page: params[:page], per_page: 4)
    # @products = Product.where(soft_delete: false).paginate(page: params[:page], per_page: 8)

    end
  end

  def category_details
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page], per_page: 4) 
  end

  def product_details
    @product = Product.find(params[:id])
    @reviews = @product.reviews.to_a
    @avg_rating = if @reviews.blank?
      0
    else
      @product.reviews.average(:rating).present? ? @product.reviews.average(:rating).round(2) : 0
    end
  end
  
   
  def bsupplier
  end

  def brequirement
  end

  def sadvertise
  end

  def spost
  end

  def cbuy
  end

  def csection
  end

  def about
  end

  def contact
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/home/category_details.html.erb
<div class="container">
  <!-- <h3 class="h3">shopping Demo-1 </h3> -->
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6" style="margin-bottom: 25px;">
        <div class="product-grid">
          <div class="product-image">
            <a href="/product_details/<%= product.id%>">
            <% if product.image.present? %>
              <%= image_tag product.image_url, class: "pic-1", style: "height:324px;width:253px"%>
            <% else %>
              <img class="pic-1" src="http://bestjquery.com/tutorial/product-grid/demo9/images/img-7.jpg">
            <% end %>
            </a>
            <ul class="social">
              <!-- <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
              <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
              <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li> -->
            </ul>
            <span class="product-new-label">Sale</span>
            <span class="product-discount-label"><%= product.price.to_i > 0 ? product.discount_percentage : 0 %></span>
          </div>
          <!-- <ul class="rating">
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star disable"></li>
          </ul> -->
          <div class="product-content">
            <h3 class="title"><a href="#"><%= product.title %></a></h3>
            <div class="price">$<%= product.try(:discount_price).to_f %>
              <span>$<%= product.try(:price).to_f %></span>
            </div>
            <a class="add-to-cart" href=""></a>
          </div>
        </div>
      </div>
      <br>
      <br>
    <% end %>
  </div>
  <br>
  <div class="pagination">
    <%= will_paginate @products %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
<%#= form_tag products_path, :method => 'get' do %>
  <!-- <p> -->
    <%#= text_field_tag :search, params[:search] %>
    <%#= submit_tag "Search", :price => nil %>
  <!-- </p> -->
<%# end %>
  <!-- <h3 class="h3">shopping Demo-1 </h3> -->
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6" style="margin-bottom: 25px;">
        <div class="product-grid">
          <div class="product-image">
            <a href="#">
            <%= link_to product_details_path(product) do %>
              <% if product.image.present? %>
                <%= image_tag product.image_url, class: "pic-1", style: "height:324px;width:253px"%>
              <% else %>
                <img class="pic-1" src="http://bestjquery.com/tutorial/product-grid/demo9/images/img-7.jpg">
                
              <% end %>
            <% end %>
            <ul class="social">
              <!-- <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
              <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
              <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li> -->
            </ul>
            <span class="product-new-label">Sale</span>
            <span class="product-discount-label"><%= product.price.to_i > 0 ? product.discount_percentage : 0 %> Off</span>
          </div>
          <!-- <ul class="rating">
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star disable"></li>
          </ul> -->
          <div class="product-content">
            <h3 class="title"><a href="#"><%= product.title %></a></h3>
            <div class="price">$<%= product.try(:discount_price).to_f %>
              <span>$<%= product.try(:price).to_f %></span>
            </div>
            <a class="add-to-cart" href="JavaScript:void(0);"></a>
          </div>
        </div>
      </div>
      <br>
      <br>
    <% end %>
  </div>
  <br>

  <div class="pagination">
    <%= will_paginate @products %>
  </div>
</div>

<style type="text/css">
  .pic-1:hover{
    
    transform: scale(1.2);
  }
</style>

app/views/home/product_details.html.erb
<div class="container">
  <div class="card">
    <div class="container-fliud">
      <div class="wrapper row">
        <div class="preview col-md-6">
          <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1">
              <% if @product.image.present? %>
              <%= image_tag @product.image_url, style: "height:309px;width:491px"%>
              <% else %>
              <img src="http://bestjquery.com/tutorial/product-grid/demo9/images/img-7.jpg" />
              <% end %>
            </div>
          </div>
        </div>
        <div class="details col-md-6">
          <h3 class="product-title"><%= @product.title %></h3>
          <div class="rating">
            <div class='star-rating' data-score="<%= @avg_rating %>"></div>
            <span class="review-no">(<%= "#{@reviews.try(:size)}" %> <%= @reviews.try(:size) == 1 ? 'review' : 'reviews'%>)</span>
          </div>
          <p class="product-description"></p>
          <h4 class="price">current price: <span>$<%= @product.price.present? ? @product.try(:discount_price).to_f : '0.0'%></span></h4>
          <!-- <p class="vote"><strong>91%</strng> of buyers enjoyed this product! <strong>(87 votes)</strong></p> -->
          <h5 class="sizes">
          size:<%= @product.size %>
          <!-- </h5>
            <h5 class="colors">colors:
              <span class="color orange not-available" data-toggle="tooltip" title="Not In store"></span>
              <span class="color green"></span>
              <span class="color blue"></span>
            </h5> -->
          <div class="action">
            <!-- <button  class="add-to-cart btn btn-default" type="button">add to cart</button> -->
            <% if user_signed_in? %>
            <% if current_cart.cart_items.where(product_id: @product.id).first.present? %>
            <%= link_to "Go to Cart", carts_path, class: 'add-to-cart btn btn-default', style: "color:white;" %>
            <% else %>
            <%= link_to 'add to cart', product_add_cart_path(@product.id), class: "add-to-cart btn btn-default", style: "color:white;" %>
            <% end %>
            <% else %>
            <%= link_to 'add to cart', product_add_cart_path(@product.id), class: "add-to-cart btn btn-default", style: "color:white;" %>
            <%#= link_to "Proceed to checkout", new_cart_order_path(@product.carts.first.id, product_id: @product.carts.first.product), class: 'add-to-cart btn btn-default' %>
            <% end %>
            <%#= link_to "Proceed to checkout", new_order_path, class: 'add-to-cart btn btn-default' %>
            <%= link_to product_add_wishlist_path(@product.id), {:class => 'like btn btn-default', style: "color:white;",'data-tip'=> 'Add to Wishlist', title: 'Add to Wishlist'} do %>
            <span class="fa fa-heart"></span>
            <% end %>
            <%= link_to product_add_favorite_path(@product.id), {:class => 'like btn btn-default', style: "color:white;",'data-tip'=> 'Add to favorite', title: 'Add to favorite'} do %>
            <span class="fa fa-star"></span>
            <% end %>
          </div>
          <br>
          <% @product.reviews.order("reviews.created_at DESC").each do |rating_review|%>
          <div class="review-block">
            <div class="row">
              <div class="col-sm-6">
                <img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
                <div class="review-block-name"><a href="#"><%= rating_review.user.email %></a></div>
                <div class="review-block-date"><%= rating_review.created_at.strftime('%d %b %Y')%><br/><%= time_ago_in_words(rating_review.created_at, include_seconds: true) %> Ago</div>
              </div>
              <div class="col-sm-6">
                <div class="review-block-rate">
                  <% (1 .. (rating_review.rating)).each do |rr|%>
                  <span class="fa fa-star" style="color: #ff9f1a;"></span>
                  <% end %>
                  <%# if rating_review.half_star? %>
                  <!-- <span class="fa fa-star half"></span> -->
                  <%# end %>
                </div>
                <div class="review-block-description"><%= rating_review.comment%></div>
              </div>
            </div>
            <hr/>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>
<style type="text/css">
  img {
  max-width: 100%; }

.preview {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

.preview-pic {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.preview-thumbnail.nav-tabs {
  border: none;
  margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
    .preview-thumbnail.nav-tabs li img {
      max-width: 100%;
      display: block; }
    .preview-thumbnail.nav-tabs li a {
      padding: 0;
      margin: 0; }
    .preview-thumbnail.nav-tabs li:last-of-type {
      margin-right: 0; }

.tab-content {
  overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
            animation-name: opacity;
    -webkit-animation-duration: .3s;
            animation-duration: .3s; }

.card {
  margin-top: 50px;
  background: #eee;
  padding: 3em;
  line-height: 1.5em; }

@media screen and (min-width: 997px) {
  .wrapper {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; } }

.details {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }

.colors {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.product-title, .price, .sizes, .colors {
  text-transform: UPPERCASE;
  font-weight: bold; }

.checked, .price span {
  color: #ff9f1a; }

.product-title, .rating, .product-description, .price, .vote, .sizes {
  margin-bottom: 15px; }

.product-title {
  margin-top: 0; }

.size {
  margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

.color {
  display: inline-block;
  vertical-align: middle;
  margin-right: 10px;
  height: 2em;
  width: 2em;
  border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

.add-to-cart, .like {
  background: #ff9f1a;
  padding: 1.2em 1.5em;
  border: none;
  text-transform: UPPERCASE;
  font-weight: bold;
  color: #fff;
  -webkit-transition: background .3s ease;
          transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: #b36800;
    color: #fff; }

.not-available {
  text-align: center;
  line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

.orange {
  background: #ff9f1a; }

.green {
  background: #85ad00; }

.blue {
  background: #0076ad; }

.tooltip-inner {
  padding: 1.3em; }

@-webkit-keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

@keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }
</style>