config/routes.rb
Rails.application.routes.draw do

  # resources :cart_items
  resources :addresses
  resources :reviews
  devise_for :users
  get 'home/index'
  get 'home/bsupplier'
  get 'home/brequirement'
  get 'home/sadvertise'
  get 'home/spost'
  get 'home/cbuy'
  get 'home/csection'
  get 'home/about'
  get 'home/contact'
  root 'home#index'
  get 'product_details/:id' => "home#product_details", as: :product_details
  get 'category_details/:id/products' => "home#category_details", as: :category_details
  get "wishlist" => "products#wishlist"
  get "favorite" => "products#favorite" 
  resources :products, except: [:new, :index, :edit, :show] do
    get :add_wishlist
    get :remove_wishlist
    get :add_favorite
    get :remove_favorite
    get :add_cart
    get :remove_cart 
    member do
      get :report_pdf
    end
  end
  get "/update_cart_item_quantity/:type/:cart_item_id" => "carts#update_cart_item_quantity", as: :update_cart_item_quantity

  get 'order_pdf' => 'orders#order_pdf'

   resources :orders
    
  resources :carts do
  # resources :orders
  end

  namespace :admin, module: nil  do
    root "admin#index"
    resources :users
    resources :products
    resources :categories
    # resources :orders
    get 'deleted_product' => 'products#deleted_product'
    get 'order_product' => 'orders#order_product'
    get 'display_report' => 'admin#display_report' 
    get 'order' => 'admin#order'

    
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user, optional: true
	 # has_many :orders, dependent: :destroy

	def full_address
		"#{address} #{district} #{country}-#{post_code}"
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
		# belongs_to :product, optional: true
		belongs_to :user, optional: true
		has_many :cart_items
		has_many :orders, dependent: :destroy
        default_scope {order("created_at desc")}
     def sub_total
     	cart_items.map(&:price).reject {|e| !e.present?}.sum	
	end
	 def quantity
     	cart_items.map(&:quantity).sum	
	end
	
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	  belongs_to :cart
	  belongs_to :product
      default_scope {order(:created_at)}
     def total_price
     	unit_price = quantity * price	
     end
     
 end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	mount_uploader :image, AvatarUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   belongs_to :product, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product, optional: true
	belongs_to :user, optional: true
	belongs_to :cart, optional: true
	has_many :reviews, dependent: :destroy
    
    # belongs_to :address, optional: true
    default_scope {order("created_at desc")}
    def full_address
    "#{address} #{district} #{country}-#{postal_code}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category, optional: true
  has_many :reviews
	mount_uploader :image, AvatarUploader
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  has_many :orders
  has_many :cart_items
  has_many :favorites, dependent: :destroy
	validate :discount_after_price?
  acts_as_paranoid
  default_scope {order("created_at desc")}
  def discount_after_price?
    if discount_price.present? 
      if discount_price.to_i > price.to_i 
        errors.add :discount_price, " ,full price must be less than"
      end
    end   
  end
  def discount_percentage
    if price.present? && price.to_i > 0 && discount_price.present? && discount_price.to_i > 0
      "" + (100 - (discount_price.to_f / price.to_f * 100.0)).round(2).to_s + "%"
    else
      "0.0"
    end
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :product, optional: true
	belongs_to :order, optional: true
	def half_star?
		if ((self.rating/2.0).to_s.split('.')[1].to_i) > 0
			true
		else
			false
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, AvatarUploader
  extend FriendlyId
  friendly_id :first_name, use: :slugged
  def is_admin?
    return true if self.role =="admin"
  end
  has_many :wishlists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :cart
  has_many :reviews, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  GENDER = {:male => "Male", :female => "Female"}

 
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :product, optional: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /carts
  # GET /carts.json
  def index
    # @carts = Cart.all 
    # product_ids = current_cart.cart_items.map(&:product_id)
    # @products = Product.where(id: product_ids)
    #  if user_signed_in?
    #   @carts = current_cart.cart_items 
    #  else
    #   redirect_to "/users/sign_in", notice: "you need to sign in or sign up"
    #  end
    current_cart.cart_items.each do |cart_item|
      if cart_item.product.nil?
        cart_item.destroy!
      end
    end 
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def update_cart_item_quantity
    cart_item = CartItem.find(params[:cart_item_id])
    if params[:type] == "increase"
      cart_item.update(quantity: cart_item.quantity + 1)
      cart_item.price = cart_item.quantity * cart_item.unit_price
      cart_item.save
    elsif params[:type] == "decrease" && cart_item.quantity != 1
      cart_item.update(quantity: cart_item.quantity - 1)
      cart_item.price = cart_item.quantity * cart_item.unit_price
      cart_item.save
    end
  end

  
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id, :product_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/carts/_cart.html.erb
<table class=" myTable table table-hover" id="cartpdf">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Category</th>
      <th>Quantity</th>
      <th>Unit_Price</th>
      <th>Price</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% if current_cart.cart_items.any? %>
    <% current_cart.cart_items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.product.title %></td>
      <td><%= cart_item.product.description %></td>
      <td><a href="/product_details/<%= cart_item.product.id%>"><%= image_tag cart_item.product.image_url, style: "height:100px;width:100px" %></a></td>
      <td><%= cart_item.product.category.title %></td>
      <td>
        <div class="row">
          <% unless cart_item.quantity.to_i == 1 %>
          <div class="text-center">
            <%= link_to "-", update_cart_item_quantity_path(type: "decrease", cart_item_id: cart_item.id), class: "btn btn-success", remote: true %>
          </div>
          <% end %>
          <div class="text-center">
            <%= text_field_tag :quantity, cart_item.quantity, style: " height:38px;", class: "text-center form-control", min: 1 %>
          </div>
          <div class="text-center">
            <%= link_to "+", update_cart_item_quantity_path(type: "increase", cart_item_id: cart_item.id), class: "btn btn-success", remote: true %>
          </div>
        </div>
      </td>
      <td><%= cart_item.unit_price %></td>
      <td><%= cart_item.price %></td>
      <td><%= link_to "Remove",  product_remove_cart_path(cart_item.product.id)  %></td>
      </div>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<br>
<div class="float-right p-2 mb-2 bg-success text-white " style="margin-right: 3%" >
  Total Price: <%= current_cart.sub_total %>
</div>
<div class="float-right p-2 mb-2 bg-success text-white " style="margin-right: 5%" >
  Total Quantity: <%= current_cart.quantity %>&nbsp;&nbsp;
</div>
<br><br>
<div class="text-center ">
  <div class="btn-group">
    <%#= button_to 'Place Order', order_path(count: @products.count, product_id: @products.ids), :class => "btn btn-info" %>&nbsp;&nbsp;
    <% if current_cart.cart_items.present? %>
    <%= link_to 'Checkout',  new_order_path, :class => "btn btn-success", style: "color:white;" %>
    <% else %>
    <a href="/" class="btn btn-success" style="color: white;">Go to Shoping</a>
    <% end %>
  </div>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Cart Item</h1>
<!-- <script src="http://localhost/assets/js/ZeroClipboard.js"></script>  -->

<div id="cart">
  <%= render "cart" %>
</div>

<style type="text/css">
  #myform {
    text-align: center;
    padding: 5px;
    border: 1px dotted #ccc;
    margin: 2%;
}
.qty {
    width: 40px;
    height: 25px;
    text-align: center;
}
input.qtyplus { width:25px; height:25px;}
input.qtyminus { width:25px; height:25px;}
</style>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @cart.product_id %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/carts/update_cart_item_quantity.js.erb
$('#cart').html("<%= escape_javascript render(:partial => 'carts/cart') %>");