config/routes.rb
Rails.application.routes.draw do

  # resources :cart_items
  resources :addresses
  resources :reviews
  devise_for :users
  get 'home/index'
  get 'home/bsupplier'
  get 'home/brequirement'
  get 'home/sadvertise'
  get 'home/spost'
  get 'home/cbuy'
  get 'home/csection'
  get 'home/about'
  get 'home/contact'
  root 'home#index'
  get 'product_details/:id' => "home#product_details", as: :product_details
  get 'category_details/:id/products' => "home#category_details", as: :category_details
  get "wishlist" => "products#wishlist"
  get "favorite" => "products#favorite" 
  resources :products, except: [:new, :index, :edit, :show] do
    get :add_wishlist
    get :remove_wishlist
    get :add_favorite
    get :remove_favorite
    get :add_cart
    get :remove_cart 
    member do
      get :report_pdf
    end
  end
  get "/update_cart_item_quantity/:type/:cart_item_id" => "carts#update_cart_item_quantity", as: :update_cart_item_quantity

  get 'order_pdf' => 'orders#order_pdf'

   resources :orders
    
  resources :carts do
  # resources :orders
  end

  namespace :admin, module: nil  do
    root "admin#index"
    resources :users
    resources :products
    resources :categories
    # resources :orders
    get 'deleted_product' => 'products#deleted_product'
    get 'order_product' => 'orders#order_product'
    get 'display_report' => 'admin#display_report' 
    get 'order' => 'admin#order'

    
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user, optional: true
	 # has_many :orders, dependent: :destroy

	def full_address
		"#{address} #{district} #{country}-#{post_code}"
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
		# belongs_to :product, optional: true
		belongs_to :user, optional: true
		has_many :cart_items
		has_many :orders, dependent: :destroy
        default_scope {order("created_at desc")}
     def sub_total
     	cart_items.map(&:price).reject {|e| !e.present?}.sum	
	end
	 def quantity
     	cart_items.map(&:quantity).sum	
	end
	
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	  belongs_to :cart
	  belongs_to :product
      default_scope {order(:created_at)}
     def total_price
     	unit_price = quantity * price	
     end
     
 end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	mount_uploader :image, AvatarUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   belongs_to :product, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product, optional: true
	belongs_to :user, optional: true
	belongs_to :cart, optional: true
	has_many :reviews, dependent: :destroy
    
    # belongs_to :address, optional: true
    default_scope {order("created_at desc")}
    def full_address
    "#{address} #{district} #{country}-#{postal_code}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category, optional: true
  has_many :reviews
	mount_uploader :image, AvatarUploader
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  has_many :orders
  has_many :cart_items
  has_many :favorites, dependent: :destroy
	validate :discount_after_price?
  acts_as_paranoid
  default_scope {order("created_at desc")}
  def discount_after_price?
    if discount_price.present? 
      if discount_price.to_i > price.to_i 
        errors.add :discount_price, " ,full price must be less than"
      end
    end   
  end
  def discount_percentage
    if price.present? && price.to_i > 0 && discount_price.present? && discount_price.to_i > 0
      "" + (100 - (discount_price.to_f / price.to_f * 100.0)).round(2).to_s + "%"
    else
      "0.0"
    end
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :product, optional: true
	belongs_to :order, optional: true
	def half_star?
		if ((self.rating/2.0).to_s.split('.')[1].to_i) > 0
			true
		else
			false
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, AvatarUploader
  extend FriendlyId
  friendly_id :first_name, use: :slugged
  def is_admin?
    return true if self.role =="admin"
  end
  has_many :wishlists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :cart
  has_many :reviews, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  GENDER = {:male => "Male", :female => "Female"}

 
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :product, optional: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @products = Product.all.paginate(page: params[:page], per_page: 4)
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to define_admin_routes({resourceName: 'Category', objectId: @category.id}), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to define_admin_routes({resourceName: 'Category', objectId: @category.id}), notice: 'Category was successfully updated.' }
         format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
     format.html { redirect_to define_admin_routes({resourceName: 'Category'}), notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description, :image, :status, :User_id, :is_active)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/categories/_form.html.erb
<div class ="container">
<div class="row">
  <%= form_for([:admin,@category]) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label for="title">title</label>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="field">
       <label for="description">description</label>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="field">
       <label for="image">image</label>
      <%= form.file_field :image, class: "form-control" %>
    </div>
    <div class="field">
       <label for="status">status</label>
      <%= form.text_field :status, class: "form-control" %>
    </div>
    <div class="field">
       <label for="is_active">is_active</label>
      <%= form.check_box :is_active, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit'create',class: "btn btn-success" %>
    </div>
  <% end %>
</div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $("input").prop('required', true);
    $("text").prop('required', true);
  });
</script>

app/views/categories/edit.html.erb
<div class ="container">

	<h1>Editing Category</h1>

	<%= render 'form', category: @category %>
	<%= link_to 'Show', polymorphic_path([:admin,  @category]) %> |

	<%= link_to 'Back', admin_category_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
<%= link_to 'New Category', new_admin_category_path,class:"btn btn-primary", style: "color:white;" %>
<table class="table">
  <thead class="thead-hover">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>image</th>
      <th>status</th>
      <th>Is_active</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <% if category.image.present? %>
         <td><%= image_tag category.image_url, height: "100", width: "100"%></td>
          <% else %>
          <td></td>
        <% end %>
        <td><%= category.status %></td>
        <td><%= category.is_active %></td>
        <td><%= link_to 'Show', polymorphic_path([:admin,  category]), :class=>"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category), :class=>"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', polymorphic_path([:admin,  category]), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="pagination">
    <%= will_paginate @products %>
  </div>

app/views/categories/new.html.erb
<div class ="container">

	<%= render 'form', category: @category %>

	<%= link_to 'Back', admin_categories_path %>
</div>

app/views/categories/show.html.erb
  <div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Image</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <td><%= @category.title %></td>
      <td><%= @category.description %></td>
      <td><%= image_tag @category.image_url, height: "100", width: "100"%></td>
      <td><%= @category.created_at %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(@category), :class=>"btn btn-info" %></td>
      <td><%= link_to 'Back', admin_categories_path, :class=>"btn btn-warning" %>
      <td>
      </tr>
    </tbody>
  </table>
</div>