config/routes.rb
Rails.application.routes.draw do

  # resources :cart_items
  resources :addresses
  resources :reviews
  devise_for :users
  get 'home/index'
  get 'home/bsupplier'
  get 'home/brequirement'
  get 'home/sadvertise'
  get 'home/spost'
  get 'home/cbuy'
  get 'home/csection'
  get 'home/about'
  get 'home/contact'
  root 'home#index'
  get 'product_details/:id' => "home#product_details", as: :product_details
  get 'category_details/:id/products' => "home#category_details", as: :category_details
  get "wishlist" => "products#wishlist"
  get "favorite" => "products#favorite" 
  resources :products, except: [:new, :index, :edit, :show] do
    get :add_wishlist
    get :remove_wishlist
    get :add_favorite
    get :remove_favorite
    get :add_cart
    get :remove_cart 
    member do
      get :report_pdf
    end
  end
  get "/update_cart_item_quantity/:type/:cart_item_id" => "carts#update_cart_item_quantity", as: :update_cart_item_quantity

  get 'order_pdf' => 'orders#order_pdf'

   resources :orders
    
  resources :carts do
  # resources :orders
  end

  namespace :admin, module: nil  do
    root "admin#index"
    resources :users
    resources :products
    resources :categories
    # resources :orders
    get 'deleted_product' => 'products#deleted_product'
    get 'order_product' => 'orders#order_product'
    get 'display_report' => 'admin#display_report' 
    get 'order' => 'admin#order'

    
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category, optional: true
  has_many :reviews
	mount_uploader :image, AvatarUploader
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  has_many :orders
  has_many :cart_items
  has_many :favorites, dependent: :destroy
	validate :discount_after_price?
  acts_as_paranoid
  default_scope {order("created_at desc")}
  def discount_after_price?
    if discount_price.present? 
      if discount_price.to_i > price.to_i 
        errors.add :discount_price, " ,full price must be less than"
      end
    end   
  end
  def discount_percentage
    if price.present? && price.to_i > 0 && discount_price.present? && discount_price.to_i > 0
      "" + (100 - (discount_price.to_f / price.to_f * 100.0)).round(2).to_s + "%"
    else
      "0.0"
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :report_pdf]
  # GET /products
  # GET /products.json
  def report_pdf
    cart_ids = @product.cart_items.joins(:cart).where(carts:{is_done:true}).map(&:cart_id)
    @orders = Order.where(cart_id: cart_ids)
     respond_to do |format|
      format.html
      format.pdf do
        render pdf: "report_pdf",   # Excluding ".pdf" extension.
        layout: "pdf.html",
        window_status: "FLAG_FOR_PDF" # Wait until window.status is equal to this string before rendering page
      end
    end
    
  end

  def index
    # @products = Product.all.paginate(page: params[:page], per_page: 4)
    @products = Product.where(soft_delete: false).paginate(page: params[:page], per_page: 4)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # @count_order = CartItem.where(product_id: @product.id)
    # @carts = Cart.where(is_done: true)
    cart_ids = @product.cart_items.joins(:cart).where(carts:{is_done:true}).map(&:cart_id)
    if params[:start_date].present? && params[:end_date].present?
      @order = Order.where(cart_id: cart_ids)
      @orders = @order.where('created_at BETWEEN ? AND ?', params[:start_date].to_date.beginning_of_day, params[:end_date].to_date.end_of_day)
    else
      @orders = Order.where(cart_id: cart_ids)
    end
    # @user_id = @count_order.where(user_id: current_user.id)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end
  def deleted_product
    @products =  Product.only_deleted
    # @products = Product.where(soft_delete: true)
     
  end 

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_root_path({resourceName: 'Product', objectId: @product.id}), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
         format.html { redirect_to admin_root_path({resourceName: 'Product', objectId: @product.id}), notice: 'Product was successfully updated.' }
         format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.update(soft_delete: true)
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_root_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_wishlist
    @product = Product.find(params[:product_id])
    if user_signed_in?
      existing_wishlist = current_user.wishlists.where(product_id: @product.id)
      if existing_wishlist.present?
        redirect_back fallback_location: root_path, notice: "Product is already in your wishlist"
      else
        current_user.wishlists.create(product_id: @product.id)
        redirect_to wishlist_path, notice: "Product has been added in to your wishlist"
      end
    else
      redirect_to "/users/sign_in", notice: "you need to sign in or sign up"
    end
  end

  def remove_wishlist
    @product = Product.find(params[:product_id])
    current_user.wishlists.where(product_id: @product.id).first.destroy
    redirect_to "/wishlist"
  end

  def wishlist
    product_ids = current_user.wishlists.map(&:product_id)
    @products = Product.where(id: product_ids)
  end


  def add_favorite
    @product = Product.find(params[:product_id])
    if user_signed_in?
      existing_favorite = current_user.favorites.where(product_id: @product.id)
      if existing_favorite.present?
        redirect_back fallback_location: root_path, notice: "Product is already in your favorite"
      else
        current_user.favorites.create(product_id: @product.id)
        redirect_to root_path, notice: "Product has been added in to your favorite"
      end
    else
      redirect_to "/users/sign_in", notice: "you need to sign in or sign up"
    end
  end

  def remove_favorite
    @product = Product.find(params[:product_id])
    current_user.favorites.where(product_id: @product.id).first.destroy
    redirect_to "/favorite"
  end

  def favorite
    product_ids = current_user.favorites.map(&:product_id)
    @products = Product.where(id: product_ids)
  end



  def add_cart
    @product = Product.find(params[:product_id])
    if user_signed_in?
      # @cart = Cart.find_or_create_by(user_id: current_user.id)
      cart_items = current_cart.cart_items.where(product_id: @product.id)
      if cart_items.present?
        item = cart_items.first
        item.quantity = item.quantity.to_i + 1
        item.price = ((item.quantity.to_i) * item.unit_price.to_i).to_f
        item.save
        redirect_back fallback_location: root_path, notice: "Product successfully added to the cart"
      else
        current_cart.cart_items.create(product_id: @product.id, unit_price: @product.discount_price.to_i, price: @product.discount_price.to_i)
        redirect_to carts_path, notice: "Cart has been added in to your cart"
      end
    else
      redirect_to "/users/sign_in", notice: "you need to sign in or sign up"
    end
  end

  def remove_cart
    @product = Product.find(params[:product_id])
    current_cart.cart_items.where(product_id: @product.id).first.destroy
    redirect_to "/carts"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
       @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :image, :price, :size, :is_active, :status, :description, :category_id, :discount_price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class ="container">
  <%= form_for([:admin,@product]) do |form| %>
    <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="field">
      <label for="category">Category</label><br>
      <%= form.select(:category_id, Category.all.collect {|u| [u.title, u.id]},{:prompt => 'Select category'}, :class=>"form-control" ) %>
    </div>
    <div class="field">
      <label for="title">title</label>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="field">
      <label for="description">description</label>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="field">
      <label for="image">image</label>
      <%= form.file_field :image, class: "form-control" %>
    </div>
    <div class="field">
      <label for="price">Full Price</label>
      <%= form.text_field :price, class: "form-control" %>
    </div>
    <div class="field">
      <label for="price">Discount Price</label>
      <%= form.text_field :discount_price, class: "form-control" %>
    </div>
    <div class="field">
      <label for="size">size</label>
      <%= form.text_field :size, class: "form-control" %>
    </div>
    <div class="field">
      <label for="is_active">is_active</label>
      <%= form.check_box :is_active %>
    </div>
    <div class="field">
      <label for="status">status</label>
      <%= form.text_field :status, class: "form-control" %>
    </div>
    <div class="actions">
      <%= form.submit'create',class: "btn btn-success" %>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $("input").prop('required', true);
    $("textarea").prop('required', true);
  });
</script>

app/views/products/deleted_product.html.erb
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Price</th>
      <th>Discount price</th>
      <th>Size</th>
      <th>Is active</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <% if product.image.present? %>
         <td><%= image_tag product.image_url, height: "100", width: "100"%></td>
          <% else %>
          <td></td>
        <% end %>
        <td><%= product.price %></td>
        <td><%= product.discount_price%></td>
        <td><%= product.size %></td>
        <td><%= product.is_active %></td>
        <td><%= product.status %></td>
        <td><%= product.deleted_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/products/edit.html.erb
<div class ="container">


	<%= render 'form', product: @product %>

	<%= link_to 'Show', polymorphic_path([:admin,  @product]) %> |

	<%= link_to 'Back', admin_product_path %>
</div>

app/views/products/favorite.html.erb
  <div class="container">
  <!-- <h3 class="h3">shopping Demo-1 </h3> -->
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6" style="margin-bottom: 25px;">
        <div class="product-grid">
          <div class="product-image">
            <a href="/product_details/<%= product.id%>">
            <% if product.image.present? %>
              <%= image_tag product.image_url, class: "pic-1", style: "height:324px;width:253px"%>
            <% else %>
              <img class="pic-1" src="http://bestjquery.com/tutorial/product-grid/demo9/images/img-7.jpg">
            <% end %>
            </a>
            <ul class="social">
            </ul>
            <span class="product-new-label">Sale</span>
            <span class="product-discount-label"><%= product.price.to_i > 0 ? product.discount_percentage : 0 %></span>
          </div>
          <!-- <ul class="rating">
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star disable"></li>
          </ul> -->
          <div class="product-content">
            <h3 class="title"><a href="#"><%= product.title %></a></h3>
            <div class="price">$<%= product.try(:discount_price).to_f %>
              <span>$<%= product.try(:price).to_f %></span>
            </div>
            <%= link_to 'Remove Product From favorite', product_remove_favorite_path(product), class: "add-to-cart"%>
          </div>
        </div>
      </div>
      <br>
      <br>
    <% end %>
  </div>
  <br>
</div>

app/views/products/index.html.erb
<div class="container">
<%= link_to 'New Product', new_admin_product_path, class:"btn btn-primary", style: "color:white;" %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Price</th>
      <th>Discount price</th>
      <th>Size</th>
      <th>Is active</th>
      <th>Status</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <% if product.image.present? %>
         <td><%= image_tag product.image_url, height: "100", width: "100"%></td>
          <% else %>
          <td></td>
        <% end %>
        <td><%= product.price %></td>
        <td><%= product.discount_price%></td>
        <td><%= product.size %></td>
        <td><%= product.is_active %></td>
        <td><%= product.status %></td>
        <td><%= product.description %></td>
       <td><%= link_to 'Show', polymorphic_path([:admin,  product]), :class=>"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product), :class=>"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', polymorphic_path([:admin,  product]), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="pagination">
    <%= will_paginate @products %>
  </div>

app/views/products/new.html.erb
<div class ="container">

	<%= render 'form', product: @product %>

	<%= link_to 'Back', admin_products_path %>
</div>

app/views/products/report_pdf.erb
  <div class="container">
  <%= area_chart @orders.group_by_day() { |order| order.created_at }.map { |date, orders| [date, orders.size] }, width: "1000px", height: "500px" %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Order Date</th>
          <th>Address</th>
          <th>Total Quantity</th>
          <th>Total Price</th>
          <th>User Name</th>
        </tr>
      </thead>
      <tbody>
       <% @orders.each do |order| %>
       <tr>
        <td><%= @product.title %></td>
        <td><%= order.user.try(:email) %></td>
        <td><%= order.created_at %></td>
        <td><%= order.address %></td>
        <td><%= order.cart.quantity %></td>
        <td><%= order.cart.sub_total %></td>
        <td><%= order.user.try(:first_name) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

app/views/products/show.html.erb
<div class="container">
  <%#= line_chart User.group_by_day(:created_at).count %>
<%= link_to 'Create PDF', report_pdf_product_path(@product,format: :pdf),class:"btn btn-primary", style: "color:white;" %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Image</th>
        <th>Price</th>
        <th>Size</th>
        <th>Description</th>
        <th>Total order</th>
      </tr>
    </thead>
    <tbody>
      <td><%= @product.title %></td>
      <td><%= image_tag @product.image_url, height: "100", width: "100"%></td>
      <td><%= @product.discount_price %></td>
      <td><%= @product.size %></td>
      <td><%= @product.description %></td>
      <td><%= @orders.count %></td>
      </tr>
    </tbody>
  </table>
  <!-- <p>
    <strong>Users Name</strong>
    <% @orders.each_with_index do |order, index |%>
    <%= order.user.first_name %><% unless index+1 == @orders.count %>,<% end %>
    <% end %>
  </p> -->
</div>
<div class="container">
  <%= area_chart @orders.group_by_day() { |order| order.created_at }.map { |date, orders| [date, orders.size] } %>
  <div class="row" style="float: right; margin-bottom: 10px;">
    <%= form_tag admin_product_path(@product), method: :get do %>
      <%= text_field_tag 'start_date', params[:start_date], placeholder: "Enter Start Date", class: "datepicker", id: "txtStartDate" %>
      <%= text_field_tag 'end_date', params[:end_date], placeholder: "Enter End Date", class: "datepicker", id: "txtEndDate" %>
      <%= submit_tag 'Search',class:"btn btn-primary", style: "color:white;" %>
    <% end %>
  </div>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>User Name</th>
        <th>Email</th>
        <th>Order Date</th>
        <th>Address</th>
        <th>Total Quantity</th>
        <th>Total Price</th>
      </tr>
    </thead>
    <tbody>
     <% @orders.each do |order| %>
     <tr>
      <td><%= order.user.try(:first_name) %></td>
      <td><%= order.user.try(:email) %></td>
      <td><%= order.created_at %></td>
      <td><%= order.address %></td>
      <td><%= order.cart.cart_items.map{|m| m.product_id == @product.id ? m.quantity : 0 }.sum %></td>
      <td><%= order.cart.cart_items.map{|m| m.product_id == @product.id ? m.price : 0 }.sum %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $(".datepicker").datepicker({ 
        format: 'd-mm-yyyy',
        autoclose: true 
    })
    .on("changeDate", function (e) {
      var start_date = $("#txtStartDate").val();
      var end_date = $("#txtEndDate").val();
      if (start_date != "" && end_date != ""){ 
        // start_date = new Date(start_date);
        // end_date = new Date(end_date); 
        if (end_date < start_date){ 
          alert("End date should be greater or equal to start Date"); 
          $(this).val(""); 
        } 
      } 
    });
  }); 
  $(document).ready(function(){
    $("input").prop('required', true);
    $("text").prop('required', false);
  });
</script> 

app/views/products/wishlist.html.erb
  <div class="container">
  <!-- <h3 class="h3">shopping Demo-1 </h3> -->
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6" style="margin-bottom: 25px;">
        <div class="product-grid">
          <div class="product-image">
            <a href="/product_details/<%= product.id%>">
            <% if product.image.present? %>
              <%= image_tag product.image_url, class: "pic-1", style: "height:324px;width:253px"%>
            <% else %>
              <img class="pic-1" src="http://bestjquery.com/tutorial/product-grid/demo9/images/img-7.jpg">
            <% end %>
            </a>
            <ul class="social">
            </ul>
            <span class="product-new-label">Sale</span>
            <span class="product-discount-label"><%= product.price.to_i > 0 ? product.discount_percentage : 0 %></span>
          </div>
          <ul class="rating">
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star"></li>
            <li class="fa fa-star disable"></li>
          </ul>
          <div class="product-content">
            <h3 class="title"><a href="#"><%= product.title %></a></h3>
            <div class="price">$<%= product.try(:discount_price).to_f %>
              <span>$<%= product.try(:price).to_f %></span>
            </div>
            <%= link_to 'Remove Product From Wishlist', product_remove_wishlist_path(product), class: "add-to-cart"%>
          </div>
        </div>
      </div>
      <br>
      <br>
    <% end %>
  </div>
  <br>
</div>